#!/bin/bash
echo "This is a file containing plot informations for HTML making purposes" > plotInfo.txt
echo "#####################################################################" >> plotInfo.txt

./../Executables_1204_2017/Caller_mzIdentML.exe files.txt 1 1 . >&log&
